---
- pkg: '@webundsoehne/nx-nest'
  description: 'A boilerplate to generate Nest.js applications from scratch.'
  schematics:
    - name: app
      description: Creates or edits a application.
    - name: component
      description: Generates default components depending on your application type.
    - name: microservice-provider
      description: Generate the microservice provider library.
    - name: backend-interfaces
      description: Generate a common library for backend interfaces.
    - name: backend-database
      description: Generate a common library for backend database.
    - name: generator
      description: Creates a single component from the given template.

- pkg: '@webundsoehne/nx-workspace'
  description: 'General purpose workspace schematic extended from the default.'
  schematics:
    - name: library
      description: Create a library.
    - name: move
      description: Move a project under a different name.
    - name: remove
      description: Remove a project from the workspace.

- pkg: '@webundsoehne/nx-tools'
  description: 'Some generic tools for nx.'
  schematics:
    - name: exports
      description: export a glob pattern from the defined file. an easy index.ts creation.
