image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - transpile
  - publish

linting:
  stage: test
  script:
    - yarn --frozen-lockfile
    - yarn lint
  tags:
    - node

transpile_code:
  stage: transpile
  script:
    - yarn --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
    expire_in: 30 minutes
  tags:
    - node
  only:
    - tags

build_image:
  stage: publish
  script:
    - yarn global add npm-cli-login
    - npm-cli-login -u $NPM_WS_USERNAME -p $NPM_WS_PASSWORD -e $NPM_WS_EMAIL
    - npm publish --access public
    - npm logout
  tags:
    - node
  only:
    - tags
